export enum DinagatUserRole {
  TRAVELER = "TRAVELER",
  OPERATOR_OWNER = "OPERATOR_OWNER",
  OPERATOR_STAFF = "OPERATOR_STAFF",
  LGU_USER = "LGU_USER",
  ADMIN = "ADMIN",
  SUPER_ADMIN = "SUPER_ADMIN"
}

export enum DinagatBookingStatus {
  DRAFT = "DRAFT",
  REQUESTED = "REQUESTED",
  OPERATOR_REVIEW = "OPERATOR_REVIEW",
  OPERATOR_ACCEPTED = "OPERATOR_ACCEPTED",
  OPERATOR_REJECTED = "OPERATOR_REJECTED",
  PAYMENT_READY = "PAYMENT_READY",
  PAYMENT_PENDING = "PAYMENT_PENDING",
  PAID = "PAID",
  CONFIRMED = "CONFIRMED",
  IN_PROGRESS = "IN_PROGRESS",
  COMPLETED = "COMPLETED",
  CANCELLED = "CANCELLED",
  EXPIRED = "EXPIRED"
}

export enum DinagatPaymentReadinessStatus {
  NOT_READY = "NOT_READY",
  REQUIRES_OPERATOR_CONFIRMATION = "REQUIRES_OPERATOR_CONFIRMATION",
  READY_FOR_PAYMENT = "READY_FOR_PAYMENT",
  PAYMENT_STARTED = "PAYMENT_STARTED",
  PAYMENT_CONFIRMED = "PAYMENT_CONFIRMED",
  PAYMENT_FAILED = "PAYMENT_FAILED",
  REFUND_REQUIRED = "REFUND_REQUIRED",
  REFUNDED = "REFUNDED"
}

export enum DinagatQrStatus {
  NOT_ISSUED = "NOT_ISSUED",
  ISSUED = "ISSUED",
  ACTIVE = "ACTIVE",
  SUSPENDED = "SUSPENDED",
  EXPIRED = "EXPIRED",
  REVOKED = "REVOKED"
}

export enum DinagatScanEventStatus {
  CREATED = "CREATED",
  VALIDATED = "VALIDATED",
  REJECTED = "REJECTED",
  DUPLICATE = "DUPLICATE",
  MANUAL_REVIEW = "MANUAL_REVIEW"
}

export enum DinagatVisitStampStatus {
  NOT_ELIGIBLE = "NOT_ELIGIBLE",
  ELIGIBLE_FROM_SCAN = "ELIGIBLE_FROM_SCAN",
  ISSUED = "ISSUED",
  REVOKED = "REVOKED"
}

export enum DinagatOperatorApprovalStatus {
  DRAFT = "DRAFT",
  SUBMITTED = "SUBMITTED",
  UNDER_REVIEW = "UNDER_REVIEW",
  APPROVED = "APPROVED",
  SUSPENDED = "SUSPENDED",
  REJECTED = "REJECTED"
}

export enum DinagatOperatorCapabilityStatus {
  NOT_REQUESTED = "NOT_REQUESTED",
  REQUESTED = "REQUESTED",
  APPROVED = "APPROVED",
  SUSPENDED = "SUSPENDED",
  REVOKED = "REVOKED"
}

export enum DinagatMarketplaceExposureStatus {
  HIDDEN = "HIDDEN",
  ELIGIBLE = "ELIGIBLE",
  EXPOSED = "EXPOSED",
  CAPPED = "CAPPED",
  SUSPENDED = "SUSPENDED"
}

export enum DinagatSiteAccessPointStatus {
  DRAFT = "DRAFT",
  ACTIVE = "ACTIVE",
  PAUSED = "PAUSED",
  SUSPENDED = "SUSPENDED",
  ARCHIVED = "ARCHIVED"
}

export enum DinagatSourceAttributionType {
  DIRECT = "DIRECT",
  LGU = "LGU",
  OPERATOR = "OPERATOR",
  OTA_PARTNER = "OTA_PARTNER",
  HOTEL_DESK = "HOTEL_DESK",
  TRAVEL_AGENCY = "TRAVEL_AGENCY",
  COMMUNITY_PARTNER = "COMMUNITY_PARTNER",
  ADMIN_CREATED = "ADMIN_CREATED"
}

export enum DinagatAuditActionType {
  CREATE = "CREATE",
  UPDATE = "UPDATE",
  APPROVE = "APPROVE",
  REJECT = "REJECT",
  SUSPEND = "SUSPEND",
  REVOKE = "REVOKE",
  VALIDATE_QR = "VALIDATE_QR",
  ISSUE_STAMP = "ISSUE_STAMP",
  CHANGE_PAYMENT_READINESS = "CHANGE_PAYMENT_READINESS",
  CHANGE_MARKETPLACE_EXPOSURE = "CHANGE_MARKETPLACE_EXPOSURE"
}